### ISSUE TITLE
Color hints exclude each other

### ISSUE THREAD

**Issue by Zel-beton** [ssyyhhrr/stewardle#5]
Impossible to solve, 30 is apparently too high when 31 is too low
![image](https://user-images.githubusercontent.com/129912495/229949991-0ededd21-d157-46d6-b123-2fe00a887284.png)

**Comment by ssyyhhrr** [comment]
Thanks for raising this issue, apologies for the **very** late reply, its likely this issue was experienced during restarts / development of the game at a time where the selected driver for the day did not persist across restarts.
