### ISSUE TITLE
Demo Site with regular outages over the past few weeks.

### ISSUE THREAD

**Issue by BenSteenson** [ssyyhhrr/stewardle#6]
The demo site ([https://stewardle.com](https://stewardle.com)) frequently shows 504 GATEWAY TIME-OUT errors through most hours of the day, sometimes being unavailable for the whole day.

**Comment by ssyyhhrr** [comment]
Thanks for raising this issue, apologies for the **very** late response, its likely the site was down due to an issue fixed in https://github.com/ssyyhhrr/stewardle/commit/930e1ec8b200d34c372302380fe719e973135c7b. 

The game is now back online at https://stewardle.com/
