### ISSUE TITLE
Demo site currently shows a 502 Bad Gateway error.

### ISSUE THREAD

**Issue by ARTCvan** [ssyyhhrr/stewardle#7]
Since the 17th of June 2024 (AEDT timezone), the demo site [(stewardle.com)](https://stewardle.com) reports backs a 502 Bad Gateway error, and has not been resolved since. This error is still occuring as of the time of this issue being submitted.

**Comment by ssyyhhrr** [comment]
Thanks for raising this issue, apologies for the delayed response, its likely the downtime was a result of changes I was making during development of the 2024 team changes: https://github.com/ssyyhhrr/stewardle/commit/bff3c89695a491b214d3012af620e312b73d38fe.

The game is now back online at https://stewardle.com/
